In [1]:
import pandas as pd

In [2]:
# read the Dataset met.csv(archive (2))
df0 = pd.read_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\DataSet\\archive (2)\\met.csv")

In [3]:
df0.head()

,Unnamed: 0,Actvitiy,Code,MET,Description
0,0,Bicycling,1004,16.0,"Bicycling, mountain, competitive racing"
1,1,Bicycling,1008,8.5,"Bicycling, BMX"
2,2,Bicycling,1009,8.5,"Bicycling, mountain, general"
3,3,Bicycling,1010,4.0,"Bicycling, <10 mph, leisure, to work or for pl..."
4,4,Bicycling,1011,6.8,"Bicycling, to/from work, self selected pace"

In [4]:
df0.columns

Index(['Unnamed: 0', 'Actvitiy', 'Code', 'MET', 'Description'], dtype='object')

In [5]:
df0.shape

(1125, 5)

In [6]:
df = df0.drop(columns=['Unnamed: 0', 'Code', 'MET',])

In [7]:
df.head()

    Actvitiy                                        Description
0  Bicycling            Bicycling, mountain, competitive racing
1  Bicycling                                     Bicycling, BMX
2  Bicycling                       Bicycling, mountain, general
3  Bicycling  Bicycling, <10 mph, leisure, to work or for pl...
4  Bicycling        Bicycling, to/from work, self selected pace

In [8]:
df.columns

Index(['Actvitiy', 'Description'], dtype='object')

In [9]:
df.to_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\Final Code\\Physical Information\\Physical Activities\\physical_activity.csv")