In [1]:
import pandas as pd

In [2]:
# read the Dataset career_recommender.csv
df0 = pd.read_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\DataSet\\career_recommender.csv")

In [3]:
df0.head()

,What is your name?,What is your gender?,What was your course in UG?,What is your UG specialization? Major Subject (Eg; Mathematics),What are your interests?,What are your skills ? (Select multiple if necessary),What was the average CGPA or Percentage obtained in under graduation?,Did you do any certification courses additionally?,"If yes, please specify your certificate course title.",Are you working?,"If yes, then what is/was your first Job title in your current field of work? If not applicable, write NA.","Have you done masters after undergraduation? If yes, mention your field of masters.(Eg; Masters in Mathematics)"
0,A.Uha Priya,Female,B.Sc,Computer Applications,Cloud computing,Python;SQL;Java,85,Yes,"Linux,Git",Yes,Software,MCA
1,Aadil,Male,B.E,Computer Science Engineering,Technology,"Critical Thinking, Analytic Thinking, SQL, Pro...",66.5,Yes,Microsoft certification,Yes,Computer Software Engineer,NaN
2,Aakriti,Female,BA,Psychology,Understand human behaviour,People management;Communication skills,64.6,Yes,Resilience psychology,No,NaN,NaN
3,Aanchal sharma,Female,MBA,Commerce,Sales/Marketing;Trading;Understand human behav...,Accounting Skills;Critical Thinking,75.525,No,No,Yes,Relationships manager,NaN
4,Aangkeeta Sarkar,Female,B.Tech,Instrumentation Engineering,Technology,\nPLC Allen Bradley;PLC Ladder Logic;LabVIEW;B...,70.68,Yes,Extreme Productivity (Blinkist Summary),Yes,Plant Instrumentation Engineer,NaN

In [4]:
df0.columns

Index(['What is your name?', 'What is your gender?',
       'What was your course in UG?',
       'What is your UG specialization? Major Subject (Eg; Mathematics)',
       'What are your interests?',
       'What are your skills ? (Select multiple if necessary)',
       'What was the average CGPA or Percentage obtained in under graduation?',
       'Did you do any certification courses additionally?',
       'If yes, please specify your certificate course title.',
       'Are you working?',
       'If yes, then what is/was your first Job title in your current field of work? If not applicable, write NA.               ',
       'Have you done masters after undergraduation? If yes, mention your field of masters.(Eg; Masters in Mathematics)'],
      dtype='object')

In [5]:
df = df0.drop(columns=['What is your name?', 'What is your gender?','Did you do any certification courses additionally?', 'If yes, please specify your certificate course title.', 'Are you working?', 'If yes, then what is/was your first Job title in your current field of work? If not applicable, write NA.               ', 'Have you done masters after undergraduation? If yes, mention your field of masters.(Eg; Masters in Mathematics)'])

In [6]:
df.head()

,What was your course in UG?,What is your UG specialization? Major Subject (Eg; Mathematics),What are your interests?,What are your skills ? (Select multiple if necessary),What was the average CGPA or Percentage obtained in under graduation?
0,B.Sc,Computer Applications,Cloud computing,Python;SQL;Java,85
1,B.E,Computer Science Engineering,Technology,"Critical Thinking, Analytic Thinking, SQL, Pro...",66.5
2,BA,Psychology,Understand human behaviour,People management;Communication skills,64.6
3,MBA,Commerce,Sales/Marketing;Trading;Understand human behav...,Accounting Skills;Critical Thinking,75.525
4,B.Tech,Instrumentation Engineering,Technology,\nPLC Allen Bradley;PLC Ladder Logic;LabVIEW;B...,70.68

In [7]:
df.columns

Index(['What was your course in UG?',
       'What is your UG specialization? Major Subject (Eg; Mathematics)',
       'What are your interests?',
       'What are your skills ? (Select multiple if necessary)',
       'What was the average CGPA or Percentage obtained in under graduation?'],
      dtype='object')

In [9]:
df.to_csv(df.to_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\Final Code\\Education Information\\Carrier recommender\\career_recommender.csv"))

',What was your course in UG?,What is your UG specialization? Major Subject (Eg; Mathematics),What are your interests?,What are your skills ? (Select multiple if necessary),What was the average CGPA or Percentage obtained in under graduation?\r\n0,B.Sc,Computer Applications,Cloud computing,Python;SQL;Java,85\r\n1,B.E,Computer Science Engineering,Technology,"Critical Thinking, Analytic Thinking, SQL, Programming, Work under Pressure, Logical Skills, Problem Solving skills",66.5\r\n2,BA,Psychology,Understand human behaviour,People management;Communication skills,64.6\r\n3,MBA,Commerce,Sales/Marketing;Trading;Understand human behaviour;Home interior design,Accounting Skills;Critical Thinking,75.525\r\n4,B.Tech,Instrumentation Engineering,Technology,"\nPLC Allen Bradley;PLC Ladder Logic;LabVIEW;Business Analysis;End-to-End ProjectManagement;Crossfunctional Team Leadership;Requirements Gathering;Lean Six Sigma;Lean six sigma blackbelt;Productivity Improvement",70.68\r\n5,B.Tech,Computer Science Engineering,Technology,"C,C++,HTML,Java",73.15\r\n6,BMS,Commerce,"Research, Sales/Marketing","Critical Thinking, Analytic Thinking, Communication Skills, Creativity Skills, Excel, Logical Skills, Interpersonal Skills, Presentation Skills, Problem Solving skills, Observation Skills, Reading",73.15\r\n7,B.Tech,Computer Science Engineering,Technology,NO,74.1\r\n8,B.Tech,Computer Science Engineering,Technology,Programming Language skills;Critical Thinking;Linux;Python;SQL;Java,69.35\r\n9,B.Sc,Physics ,Research;Teaching;Technology;Understand human behaviour;Understand human body;Content Writing;Govt. Job;Service;Infrastructure,Active Listening;Critical Thinking;Gathering Information;Artistic/Creative Skills;Communication skills;Leadership;Editing;Problem Solving skills;Writing skills;Medical knowledge;HR;Good communication skills;Teaching,86.45\r\n10,B.Com,Accountancy,Financial Analysis,"Accounting Skills, Analytic Thinking, Cost Accounting, Team work, Excel, Problem Solving skills, Writing, Tableau",63.745\r\n11,BE,Automobile Engineering,"Take risk for Profits, Technology, Entrepreneurship","Analytic Thinking, Gathering Informing, Communication Skills, Team work, Presentation Skills, Problem Solving skills",71.44\r\n12,MBA,Marketing ,"Sales/Marketing;Trading;Understand human behaviour;Digital marketing;Market reserach;Agriculture, services;Construction Manegement",Accounting Skills;Business Knowledge;Leadership;Problem Solving skills;Wealth Management,59\r\n13,BE,Automation,Data analytics,Critical Thinking;Gathering Information;Presentation Skills;Python;SQL;Good communication skills,69.35\r\n14,BCA,Computer Applications,Technology,Communication skills;Writing skills;C++;Python;SQL;Java;Cloud Computing,71.2\r\n15,BE,"Science,Maths, Engineering subject",Research;Technology;Data analytics;Govt. Job,Analytical Skills;Data Visualization skills( Power Bi/ Tableau );Machine Learning skills;Python;SQL,69.35\r\n16,B.Tech,Computer Science Engineering,Financial Analysis;Research;Data analytics;Data scientist,Programming Language skills;Critical Thinking;Gathering Information;Leadership;Machine Learning skills;Python;Artificial Intelligence;SQL;Java;MATLAB;Good communication skills,64.6\r\n17,BE,Mechanical Engineering,Entrepreneurship,"Python, Critical Thinking, Analytic Thinking, Gathering Informing, SQL, Programming, Leadership, Product Knowledge, Cost Accounting, Market Study, Team work, Excel, Logical Skills, R, Problem Solving skills, Writing, Tableau",71.25\r\n18,B.Tech,Electrical and Electronics Engineering,Technology,Matlab ;Embedded C; Arduino; C ++;c ;AVR;Eagle PCB;ARM Cortex-M;KiCAD;Software Project Management,81.7\r\n19,BE,Structural Engineeeing ,Research;Teaching;Technology;Data analytics,"Active Listening;Critical Thinking;Analytical Skills;People management;Communication skills;Leadership;Problem Solving skills;Designing skills;Proeficiency in Software like STAAD PRO, ETABS ",74.33\r\n20,M.Tech,Mining,Teaching;Technology;Industires,Hardware skills,92\r\n21,B.Tech,Computer Science Engineering,Financial Analysis;Research;Sales/Marketing;Technology;Data analytics,Business Knowledge;Analytical Skills;Product knowledge;Problem Solving skills;Risk management skills;Designing skills;Machine Learning skills;Python;SQL;Cloud Computing;HR,61.75\r\n22,B.Tech,Mechanical Engineering,Technology;All fields related to Data science.;Industires;Information Technology,"Proeficiency in Software like STAAD PRO, ETABS;CAD/CAE(autocad/catia/ansys/proE/SeimensNX)",73.15\r\n23,B.Com,Accountancy ,Financial Analysis;News Coverage;Research;Sales/Marketing;Social Justice;Teaching;Technology;Trading;Understand human behaviour;Understand human body;Supply Chain Analysis;Data analytics;Govt. Job;Game industry;Digital marketing,Accounting Skills;Active Listening;Critical Thinking;Gathering Information;Business Knowledge;Analytical Skills;Finance related skills;People management;Communication skills;Negotiation skills;Mass Communication;Leadership;Product knowledge;Problem Solving skills;Risk management skills;Data Visualization skills( Power Bi/ Tableau );Sales;Interpersonal skills;Wealth Management,80\r\n24,BCA,C language,Technology;Service,Programming Language skills;Communication skills;Writing skills;Machine Learning skills;Sales;C++;R,76.95\r\n25,BCA,"C,c++, java",Teaching,Active Listening;Teaching,69\r\n26,B.Tech,Civil Engineering,Market reserach,Business Knowledge;Civil & Criminal Law;Product knowledge,74.955\r\n27,B.Tech,Mechanical Engineering,Design,Critical Thinking;Problem Solving skills;Designing skills;Interpersonal skills;Python,73.15\r\n28,BBA,Management,Financial Analysis,Strategic Planning;Financial Analysis;Financial Modeling;Marketing Strategy;Financial Services,73.625\r\n29,BE,Automobile Engineering,"Financial Analysis, Sales/Marketing, Technology, Entrepreneurship","Business Knowledge, People Management, Communication Skills, Work under Pressure, Leadership, Market Study, Team work, Interpersonal Skills, Presentation Skills, Designing Skills, Sales, Design and analysis of automobile components, vehicle maintenance and reconditioning, design for manufacturer and assemble",84.55\r\n30,BE,Electronics and Communication Engineering,Embedded design,"Creativity Skills, Excel, Logical Skills, Observation Skills, Risk Managing, Designing Skills, Vlsi design,simulation,embedded,IOT",81.795\r\n31,B.Tech,Computer Science Engineering,Research,"Python, Critical Thinking, Analytic Thinking, Java, SQL, Programming, Communication Skills, Negotiation Skills, Creativity Skills, Excel, Logical Skills, Interpersonal Skills, Presentation Skills, C++",75.05\r\n32,BE,Electronics and Communication Engineering,Technology,NO,66.5\r\n33,B.Com,Sales and marketing,Sales/Marketing,Active Listening;Business Knowledge;Communication skills;Negotiation skills;Leadership;Product knowledge;Problem Solving skills;Sales;Interpersonal skills,55\r\n34,B.Com,Economics,Sales/Marketing,Business Knowledge,85\r\n35,B.Tech,Computer Science Engineering,Software Job,NO,76\r\n36,B.Tech,Computer Science Engineering,Financial Analysis;Technology;Trading;Data analytics,Business Knowledge;Analytical Skills;Negotiation skills;Problem Solving skills;Data Visualization skills( Power Bi/ Tableau );Machine Learning skills;SQL,76.475\r\n37,BE,Mechanical Engineering,Trading,Active Listening;Business Knowledge;Risk management skills;Sales;Good communication skills,63\r\n38,B.Tech,Computer science and business system,Financial Analysis;Technology;Web Designing;Web development;Social causes,Accounting Skills;Programming Language skills;Critical Thinking;Business Knowledge;Analytical Skills;Finance related skills;Communication skills;Problem Solving skills;C++;Python;SQL,87.59\r\n39,B.Pharmacy,Pharmacy,Research,"Active Listening, Creativity Skills, Team work, Logical Skills",72\r\n40,B.Com,Commerce,Financial Analysis,"Accounting Skills, Cost Accounting",51.3\r\n41,B.Sc,Interior design,Home interior design,Programming Language skills;People management;Mass Communication;Leadership;Designing skills;Writing skills;Architecture,74\r\n42,B.Com,Commerce,Take risk for Profits,"Business Knowledge, Product Knowledge, Team work, Sales",57\r\n43,B.Tech,Information Technology,Entrepreneurship,"Gathering Informing, People Management, Communication Skills, Work under Pressure, Leadership, Team work, Interpersonal Skills, Mass Communication, Observation Skills, Risk Managing",65.55\r\n44,B.Sc,Chemistry,Government jobs,Sports,74.1\r\n45,Bca,Computer Applications,Technology,"AI, ML, Python, Java, SQL, Tableau",76\r\n46,BE,Automobile Engineering,"Research, Take risk for Profits, Understand Human Behaviour","Critical Thinking, Analytic Thinking, Product Knowledge, Team work, Excel, Observation Skills, Risk Managing, Reporting, Reading, Designing Skills",76\r\n47,B.Tech,Electrical and Electronics Engineering,"Information Technology,Blockchain","\nDocker;Kubernetes;Amazon Web Services (AWS);Bash;Apache;\nNew Relic APM;Jenkins;Internet Information Services (IIS);Terraform;AKS;Continuous Integration and Continuous Delivery (CI/CD);Amazon EC2",74.67\r\n48,B.Tech,Computer Science Engineering,Software Job,"Full stack, java, python, reactjs",74.1\r\n49,BE,Mechanical Engineering,Supply Chain Analysis;Data scientist;Machine Learning;Excel,Active Listening;Analytical Skills;Negotiation skills;Product knowledge;Problem Solving skills;Risk management skills;Machine Learning skills;Python,88.35\r\n50,B.Tech,Computer Science Engineering,Software Job,"Web development (PHP, codeigniter), java development, graphic desiging, Android app development",73.15\r\n51,B.Tech,Mechanical Engineering,Trading;Data analytics;Govt. Job;Data scientist,Data Visualization skills( Power Bi/ Tableau );Python;SQL,78.185\r\n52,B.Com,Commerce ,Financial Analysis,Accounting Skills;Active Listening;Critical Thinking;Gathering Information;Artistic/Creative Skills;Business Knowledge;Communication skills;Social Media Marketing,63\r\n53,B.Sc,Physics,Technology,"Accounting Skills, Active Listening, AI, Python, Critical Thinking, Programming, Product Knowledge, Creativity Skills, Team work, Excel, Logical Skills, Presentation Skills, Problem Solving skills, Observation Skills, Risk Managing, Reading",68.685\r\n54,B.Tech,Mechanical Engineering,Technology;Industires,CAD/CAE(autocad/catia/ansys/proE/SeimensNX),74.1\r\n55,M.Tech,Electronics and Communication Engineering,Research;Sales/Marketing;Teaching;Technology;Web Designing;Content Writing;Data analytics;Digital marketing;Data scientist;Web development;Market reserach;Social media marketing;Gardening;Service;Design;Information Technology;Machine Learning;Excel,Programming Language skills;Analytical Skills;Communication skills;Leadership;Editing;Problem Solving skills;Designing skills;Writing skills;Machine Learning skills;Sales;Social Media Marketing;R;Python;Artificial Intelligence;SQL;Architecture;MATLAB;Good communication skills;Teaching;AWS;PHP;Programming Language C;Javascript,87\r\n56,B.Sc,Statistics ,Data analytics,Critical Thinking;Analytical Skills;Leadership;Problem Solving skills;Machine Learning skills;Python,69.35\r\n57,B.Tech,Computer Science Engineering,IT field\xa0,"Python, Java, SQL, Programming, Problem Solving skills",69\r\n58,B.Sc,Information TechNAlogy,"Research, Technology","Active Listening, AI, ML, Python, Analytic Thinking, Editing, Creativity Skills, Team work, C++, Problem Solving skills, Mass Communication",89.87\r\n59,B.Com,Commerce ,Blockchain,Artistic/Creative Skills,60\r\n60,BE,Industrial Engineering ,Financial Analysis;Research;Trading;Understand human behaviour;Understand human body;Data analytics;Data scientist;Gardening,Critical Thinking;Gathering Information;Business Knowledge;Analytical Skills;Finance related skills;People management;Civil & Criminal Law;Communication skills;Negotiation skills;Leadership;Product knowledge;Problem Solving skills;Risk management skills;Data Visualization skills( Power Bi/ Tableau );Machine Learning skills;Interpersonal skills;Python;SQL,72\r\n61,B.Tech,Mechanical Engineering,Technology;Supply Chain Analysis,Business Knowledge;Negotiation skills;Product knowledge;Sales,60.8\r\n62,Diploma,High pressure die casting ,Technology,Designing skills,70\r\n63,B.Com,Accounting&Finance,Financial Analysis,Company Law;Company Secretarial Work;Due Diligence;Corporate Law;industrial and labour law;company law;Corporate Social Responsibility;Public Company Compliance;Statutory Compliances;Regulatory Compliance,83.03\r\n64,B.Tech,Computer Science Engineering ,Research;Technology;Data analytics;Design,Active Listening;Programming Language skills;Communication skills;Client management;Good communication skills,68.02\r\n65,B.Tech,Computer Science Engineering,Teaching;Technology;Web Designing,Active Listening;Programming Language skills;Gathering Information;Mass Communication;Content creation,68.4\r\n66,B.E,Information Technology,"Technology, Understand Human Behaviour, Understand Human Body","Analytic Thinking, Gathering Informing, SQL, Risk Managing",76\r\n67,B.Sc,Computer Science ,Technology;Data analytics;Data scientist;All fields related to Data science.,Analytical Skills;Data Visualization skills( Power Bi/ Tableau );Python;SQL,66.5\r\n68,B.Sc,Computer Science ,Digital marketing;Market reserach,Business Knowledge;Analytical Skills;People management;Communication skills;Leadership;Product knowledge;Problem Solving skills;Risk management skills;Designing skills;Writing skills;Data Visualization skills( Power Bi/ Tableau );Presentation Skills;SQL;Hospitality;HR;Excel,75\r\n69,B.Tech,Mathematics,"Teaching, Technology","Analytic Thinking, Logical Skills, C++, Writing",71.25\r\n70,BCA,Computer Applications,Technology,Active Listening;Negotiation skills,71.25\r\n71,B.Tech,Information Technology,Technology,"Java, SQL, Programming",76\r\n72,B.Tech,Electrical and Electronics Engineering,Software Job,stack web development,78.85\r\n73,BE,Electrical and Electronics Engineering,All fields related to Data science.;Machine Learning;Sports Industry,Programming Language skills;Business Knowledge;Analytical Skills;Communication skills;Python;SQL,73.53\r\n74,B.Tech,Computer Science Engineering,Data scientist;Machine Learning,Programming Language skills;Data Visualization skills( Power Bi/ Tableau );Machine Learning skills;C++;R;Linux;Python;Artificial Intelligence;SQL;Java,73.625\r\n75,B.Com,Accounting(business and management) ,Financial Analysis;Research;Sales/Marketing;Digital marketing,Critical Thinking;Business Knowledge;Communication skills;Negotiation skills;Artificial Intelligence,85.69\r\n76,MBA,Sales and Marketing,Sales/Marketing,Business Knowledge;People management;Communication skills;Product knowledge;Sales;Social Media Marketing,72\r\n77,B.Tech,Civil Engineering,"Product Life cycle Management,","Agile Methodologies;Usability Testing;C++;Microsoft OfficeBentley InRoadsProduct Requirements;User Stories;Metrics;Product Management;Product Innovation;User Experience (UX);Research;Business Development;Digital Marketing;\n",72.675\r\n78,B.Tech,Electrical and Electronics Engineering,Technology,"\nPower Electronics;Simulink;Inverters;Matlab;PLC;Variable Frequency Drives;Switchgear;Industrial Control",79.8\r\n79,B.Sc,Computer science ,Technology;Data analytics,Programming Language skills;People management;Communication skills;Editing;C++;SQL,78\r\n80,B.Tech,Computer Science Engineering ,Web development,Active Listening;Hardware skills;Programming Language skills;Critical Thinking;Gathering Information,71\r\n81,B.Tech,Computer Science Engineering,Technology;Supply chain analysis,Analytical Skills;Machine Learning skills;Python;Artificial Intelligence;SQL,85\r\n82,BE,Civil Engineering ,Financial Analysis;Data analytics;Home interior design;All fields related to Data science.;Construction;Construction Manegement;Project Management,Gathering Information;People management;Communication skills;Problem Solving skills;Sales;Python;Javascript;construction management,68.495\r\n83,Law Hons  ,Statistics,Understand human behaviour,Active Listening;People management;Civil & Criminal Law;Negotiation skills;Machine Learning skills,61.4\r\n84,B.Tech,Criminal manual,"Research, Sales/Marketing, Technology, Entrepreneurship","Analytic Thinking, Product Knowledge, Team work, Logical Skills",68.4\r\n85,B.Tech,Mechanical Engineering,Research;Technology;Supply Chain Analysis;Govt. Job,Active Listening;Hardware skills;Critical Thinking;Gathering Information;Artistic/Creative Skills;People management;Communication skills;Negotiation skills;Mass Communication;Leadership;Editing;Product knowledge;Problem Solving skills;Risk management skills;Writing skills;Social Media Marketing;Presentation Skills;Hospitality;HR;Client management,72.675\r\n86,B.Tech,Electrical and Electronics Engineering,Research;Teaching;Technology;Trading,Accounting Skills;Active Listening;Communication skills;Product knowledge;Problem Solving skills,52\r\n87,BE,Electrical and Electronics Engineering,Research;Teaching;Technology;Trading;Understand human behaviour;Understand human body;Data scientist;Market reserach;Social media marketing;Industires,Programming Language skills;Critical Thinking;Analytical Skills;Problem Solving skills;Python;Medical knowledge;MATLAB;Teaching,62.26\r\n88,B.Tech,Mechanical Engineering,Market reserach;SAP Consultant in MM;Project Management,Business Knowledge;Analytical Skills;Finance related skills;Problem Solving skills;Risk management skills;Presentation Skills,80.75\r\n89,B.Tech,Electrical and Electronics Engineering,Data analytics,Analytical Skills;Data Visualization skills( Power Bi/ Tableau );Machine Learning skills;Social Media Marketing;R;Python;Artificial Intelligence,63.9\r\n90,B.Tech,Mechanical engineering ,"Trading,Web Designing,Content Writing,Web development,Social media marketing",C++;Hadoop;Java;SQL;Core Java;JavaScript;PL/SQL;Informatica,80.37\r\n91,B.Com,Computer Science Engineering,Financial Analysis,Accounting Skills,91.2\r\n92,B.E,Accountancy,Entrepreneurship,"Active Listening, Python, Gathering Informing, Programming",88.35\r\n93,Law Hons,Agriculture,"Financial Analysis;Social causes;Information Technology;Agriculture, services;Excel",Accounting Skills;Finance related skills;Civil & Criminal Law;Negotiation skills;Risk management skills,67\r\n94,B.Tech,Company law,Data Analytics,"JavaScript,Python",73.15\r\n95,B.Sc,Electrical and Electronics Engineering,Research,Subject Knowledge,52.25\r\n96,B.Tech,Physics,Data Analytics,Javascript,65.55\r\n97,B.Tech,Computer Science Engineering,Technology,Python,70.3\r\n98,B.Tech,Computer Applications,Technology;Information Technology ,Hardware skills;Programming Language skills;Communication skills;Problem Solving skills;Risk management skills;Writing skills;Presentation Skills;Linux;Python;Java;Cloud Computing,71.25\r\n99,B.Com,Computer Science Engineering,Financial Analysis,"\nTeamwork;Time Management;Company Secretarial Work;Legal Compliance;Communication;TeamLeadership;Interpersonal Skills;Presentations;Interpersonal Communication;Companies Act;Indirect Taxation",67.45\r\n100,B.Tech,Accounting&Finance,Teaching;Technology;Data analytics;Govt. Job;Data scientist;All fields related to Data science.;Design;Machine Learning;Navy Defence related;Oil and Gas,Accounting Skills;Active Listening;Critical Thinking;Analytical Skills;People management;Communication skills;Problem Solving skills;Python;Teaching,80.275\r\n101,BBA,Electrical Machines,Financial Analysis,Financial Modeling;Financial Analysis;,84.55\r\n102,B.Tech,Finance,"Research,Understand human body,BioTechnology","\nMicrobiology; cell culture ;molecular Biology; bioprocess;\nKatte virus",83.22\r\n103,B.E,Biotechnology,Data Analytics,"Analytic Thinking, SQL, Oracle, Communication Skills, Work under Pressure, Leadership, Excel, Interpersonal Skills, Problem Solving skills, Reporting",88.16\r\n104,B.Com,Automobile Engineering,Information Technology,Cloud Computing,47\r\n105,B.Com,Accountancy,Sales/M