In [2]:
import pandas as pd

In [3]:
# read the Dataset student_data_extended.csv
df0 = pd.read_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\DataSet\\student_data_extended.csv")

In [4]:
df0.head()

,StudentID,Name,AcademicInterest,ExtracurricularActivities,Skills,Location,YearOfStudy,Major,GPA,Languages,ClubMemberships,ResearchInterests
0,1,Student 1,Psychology,Debate Club,Problem Solving,New York,Freshman,Psychology,3.27,"Chinese, Japanese, Spanish, German, French","Music Club, Art Club, Sports Team, Debate Club...",Biomedical Engineering
1,2,Student 2,Psychology,Debate Club,"Leadership, Problem Solving, Public Speaking, ...",Boston,Graduate,Physics,3.17,"French, English, Chinese, Spanish, Japanese","Art Club, Music Club, Sports Team, Coding Club",Urban Planning
2,3,Student 3,History,Volunteer Group,"Data Analysis, Leadership, Public Speaking, Ar...",Chicago,Junior,Biology,2.09,"Spanish, Japanese, German, French","Music Club, Art Club, Debate Club, Volunteer G...",Nanotechnology
3,4,Student 4,Computer Science,Volunteer Group,"Public Speaking, Data Analysis, Problem Solving",Chicago,Graduate,Biology,2.56,"Japanese, Chinese, Spanish, French","Sports Team, Volunteer Group",Space Exploration
4,5,Student 5,Computer Science,Sports Team,Data Analysis,Chicago,Graduate,Computer Science,2.01,English,"Sports Team, Volunteer Group, Music Club",Climate Change

In [5]:
df0.columns

Index(['StudentID', 'Name', 'AcademicInterest', 'ExtracurricularActivities',
       'Skills', 'Location', 'YearOfStudy', 'Major', 'GPA', 'Languages',
       'ClubMemberships', 'ResearchInterests'],
      dtype='object')

In [6]:
df = df0.drop(columns=['StudentID', 'Name', 'AcademicInterest',
    'Skills', 'Location', 'YearOfStudy', 'Major', 'GPA', 'Languages',
    'ResearchInterests'])

In [7]:
df.head()

  ExtracurricularActivities                                    ClubMemberships
0               Debate Club  Music Club, Art Club, Sports Team, Debate Club...
1               Debate Club     Art Club, Music Club, Sports Team, Coding Club
2           Volunteer Group  Music Club, Art Club, Debate Club, Volunteer G...
3           Volunteer Group                       Sports Team, Volunteer Group
4               Sports Team           Sports Team, Volunteer Group, Music Club

In [8]:
df.columns

Index(['ExtracurricularActivities', 'ClubMemberships'], dtype='object')

In [10]:
df.to_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\Final Code\\Extra Curricular Activities Information\\Student Data Extended\\student_data_extended.csv")