In [1]:
import pandas as pd

In [2]:
# read the Dataset impact_of_extracurricular_activites_on_academic_performance_of_students.csv
df0 = pd.read_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\DataSet\\impact_of_extracurricular_activites_on_academic_performance_of_students.csv")

In [3]:
df0.head()

  Student_ID    Extracurricular_Activity   GPA  Wellbeing_Score
0      S0001  Volunteer Work (Low Hours)  2.78              5.8
1      S0002     Sports (High Intensity)  3.43              6.2
2      S0003     Sports (High Intensity)  2.44              5.0
3      S0004  Volunteer Work (Low Hours)  3.13              6.3
4      S0005    Clubs (High Involvement)  2.88              6.3

In [4]:
df0.columns

Index(['Student_ID', 'Extracurricular_Activity', 'GPA', 'Wellbeing_Score'], dtype='object')

In [5]:
df  = df0.drop(columns=['Student_ID', 'GPA', 'Wellbeing_Score'])

In [6]:
df.head()

     Extracurricular_Activity
0  Volunteer Work (Low Hours)
1     Sports (High Intensity)
2     Sports (High Intensity)
3  Volunteer Work (Low Hours)
4    Clubs (High Involvement)

In [7]:
df.columns

Index(['Extracurricular_Activity'], dtype='object')