In [1]:
import pandas as pd

In [2]:
# read the Dataset random_fitness_dataset.csv(archive (4))
df0 = pd.read_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\DataSet\\archive (4)\\random_fitness_dataset.csv")

In [3]:
df0.head()

,record_id,timestamp,user_id,age,gender,activity_type,duration_min,calories_burned,heart_rate_avg,steps,sleep_hours,weight_kg
0,1,2025-07-22 09:22:54,U026,67,Male,Cycling,7,322,175,3591,7.0,84.3
1,2,2025-05-28 13:53:54,U039,16,Female,Strength Training,83,265,113,22312,5.7,79.6
2,3,2025-08-07 01:36:54,U046,62,Female,Cycling,118,508,98,5418,6.6,88.3
3,4,2025-07-17 01:56:54,U048,56,Female,Swimming,75,270,150,19809,7.9,69.0
4,5,2025-08-11 03:22:54,U042,42,Other,Yoga,76,308,141,12562,5.0,61.6

In [4]:
df0.columns

Index(['record_id', 'timestamp', 'user_id', 'age', 'gender', 'activity_type',
       'duration_min', 'calories_burned', 'heart_rate_avg', 'steps',
       'sleep_hours', 'weight_kg'],
      dtype='object')

In [8]:
df = df0.drop(columns=['record_id', 'timestamp', 'user_id', 'age', 'gender',
    'calories_burned', 'heart_rate_avg', 'steps'])

In [9]:
df.head()

       activity_type  duration_min  sleep_hours  weight_kg
0            Cycling             7          7.0       84.3
1  Strength Training            83          5.7       79.6
2            Cycling           118          6.6       88.3
3           Swimming            75          7.9       69.0
4               Yoga            76          5.0       61.6

In [10]:
df.columns

Index(['activity_type', 'duration_min', 'sleep_hours', 'weight_kg'], dtype='object')

In [11]:
df.shape

(200, 4)

In [ ]:
df.to_csv()