In [2]:
import pandas as pd

In [3]:
# read the Dataset Data_renamed.csv
df0 = pd.read_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\DataSet\\Data_renamed.csv")

In [4]:
df0.head()

,Student Age,Sex,Graduated High School Type,Scholarship Type,Additional Work,Regular Artistic or Sports Activity,Has Partner,Total Salary,Transportation to University,Accommodation Type,...,Midterm Preparation (When),Taking Notes in Class,Listening in Class,Discussion Improves Success,Flip Classroom Usefulness,Last Semester CGPA,Expected Graduation CGPA,30,COURSE ID,GRADE
0,STUDENT1,2,2,3,3,1,2,2,1,1,...,1,1,3,2,1,2,1,1,1,1
1,STUDENT2,2,2,3,3,1,2,2,1,1,...,1,1,3,2,3,2,2,3,1,1
2,STUDENT3,2,2,2,3,2,2,2,2,4,...,1,1,2,2,1,1,2,2,1,1
3,STUDENT4,1,1,1,3,1,2,1,2,1,...,1,2,3,2,2,1,3,2,1,1
4,STUDENT5,2,2,1,3,2,2,1,3,1,...,2,1,2,2,2,1,2,2,1,1

In [5]:
df0.columns

Index(['Student Age', 'Sex', 'Graduated High School Type', 'Scholarship Type',
       'Additional Work', 'Regular Artistic or Sports Activity', 'Has Partner',
       'Total Salary', 'Transportation to University', 'Accommodation Type',
       'Mother Education', 'Father Education', 'Number of Siblings',
       'Parental Status', 'Mother Occupation', 'Father Occupation',
       'Weekly Study Hours', 'Reading Frequency (Non-Scientific)',
       'Reading Frequency (Scientific)', 'Seminars / Conferences Attendance',
       'Impact of Projects on Success', 'Class Attendance',
       'Midterm Preparation (With Whom)', 'Midterm Preparation (When)',
       'Taking Notes in Class', 'Listening in Class',
       'Discussion Improves Success', 'Flip Classroom Usefulness',
       'Last Semester CGPA', 'Expected Graduation CGPA', '30', 'COURSE ID',
       'GRADE'],
      dtype='object')

In [6]:
df = df0.drop(columns=['Student Age', 'Sex', 'Graduated High School Type','Additional Work', 'Regular Artistic or Sports Activity', 'Has Partner', 'Total Salary', 'Transportation to University', 'Accommodation Type', 'Mother Education', 'Father Education', 'Number of Siblings', 'Parental Status', 'Mother Occupation', 'Father Occupation','Reading Frequency (Non-Scientific)',
    'Reading Frequency (Scientific)', 'Seminars / Conferences Attendance',
    'Impact of Projects on Success', 'Class Attendance',
    'Midterm Preparation (With Whom)', 'Taking Notes in Class', 'Listening in Class',
    'Discussion Improves Success', 'Flip Classroom Usefulness',
    'Last Semester CGPA', 'Expected Graduation CGPA', '30', 'COURSE ID',
    'GRADE'])

In [7]:
df.head()

   Scholarship Type  Weekly Study Hours  Midterm Preparation (When)
0                 3                   5                           1
1                 3                   1                           1
2                 2                   1                           1
3                 1                   1                           1
4                 1                   4                           2

In [8]:
df.columns

Index(['Scholarship Type', 'Weekly Study Hours', 'Midterm Preparation (When)'], dtype='object')

In [9]:
df.to_csv("C:\\Users\\HIMPADMA\\OneDrive\\Desktop\\Dokumen\\University Work\\U'rWay\\U'rWay Personality Classification\\Final Code\\Education Information\\Higher_Edu_Std_Perf_Eval\\higher_edu_std_perf_eval.csv")