In [29]:
import pandas as pd
import numpy as np

In [30]:
df_1 = pd.read_csv('UrWay_Expanded_Dataset1.csv')
df_2 = pd.read_csv('UrWay_Expanded_Dataset2.csv')
df_3 = pd.read_csv('UrWay_Expanded_Dataset3.csv')
df_4 = pd.read_csv('UrWay_Expanded_Dataset4.csv')
df_5 = pd.read_csv('UrWay_Expanded_Dataset5.csv')
df_6 = pd.read_csv('UrWay_Deep_Dataset6.csv')
df_7 = pd.read_csv('UrWay_Deep_Dataset7.csv')

In [31]:
print("Dataset 1 shape:", df_1.shape)
print("Dataset 2 shape:", df_2.shape)
print("Dataset 3 shape:", df_3.shape)
print("Dataset 4 shape:", df_4.shape)
print("Dataset 5 shape:", df_5.shape)
print("Dataset 6 shape:", df_6.shape)
print("Dataset 7 shape:", df_7.shape)

Dataset 1 shape: (4048, 2)
Dataset 2 shape: (600, 2)
Dataset 3 shape: (1824, 2)
Dataset 4 shape: (2500, 2)
Dataset 5 shape: (3500, 2)
Dataset 6 shape: (4112, 3)
Dataset 7 shape: (3988, 3)

In [32]:
df_1 = df_1.sample(frac=1, random_state=42).reset_index(drop=True)
df_2 = df_2.sample(frac=1, random_state=42).reset_index(drop=True)
df_3 = df_3.sample(frac=1, random_state=42).reset_index(drop=True)
df_4 = df_4.sample(frac=1, random_state=42).reset_index(drop=True)
df_5 = df_5.sample(frac=1, random_state=42).reset_index(drop=True)
df_6 = df_6.sample(frac=1, random_state=42).reset_index(drop=True)
df_7 = df_7.sample(frac=1, random_state=42).reset_index(drop=True)
print("Shuffling completed.")

Shuffling completed.

In [33]:
df = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7], ignore_index=True)
print("Combined dataset shape:", df.shape)

Combined dataset shape: (20572, 3)

In [34]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)
print("Final shuffling completed.")

Final shuffling completed.

In [35]:
df.sample(20)

,title,Category,SubTopic
14422,My coding routine while I was in college #codi...,Data Structures and Algorithms for Placements,NaN
12539,"Transfer, Approve, TransferFrom methods in ERC20",Blockchain and Solidity Programming,ERC20 and ERC721 Token Standards
19436,Tutorial 42 - Ensemble: What is Bagging (Boots...,Machine Learning and Deep Learning Course,Ensemble Learning Techniques
2557,‘The Godfather’ doesn’t Scare You as Much As ‘...,"Entertainment: Music, Movies, Comedy, Trailers...",NaN
2537,12-Lead ECG Interpretation | Medical Physiolog...,Medical,Cardiology and ECG Interpretation
2812,"🔴CSK vs MI LIVE: Chennai vs Mumbai live, 44th ...",Sports Highlights and Cricket Match Updates,NaN
5649,Gang of Ghosts | Hindi Movies 2025 Full Movie ...,"Entertainment: Music, Movies, Comedy, Trailers...",NaN
4606,Instagram clone used firebase flutter applicat...,Flutter and Firebase App Development,NaN
19169,The Average Chicken Jockey Theater Experience,"Entertainment: Music, Movies, Comedy, Trailers...",NaN
8084,What is Docker And How Does It Work? | Docker ...,Cloud Computing AWS Azure,Docker Containerization
15230,Ultimate DSA Roadmap 2024: Master Data Structu...,Data Structures and Algorithms for Placements,NaN
18202,Macro 3.8 &amp; 3.9 Fiscal Policy and Automati...,Commerce,Macroeconomics and Fiscal Policy
14658,Peritoneum folds #anatomy #abdomen,Human Anatomy and Physiology Lectures,NaN
10310,പഞ്ചാബ് - ഹൈദരാബാദ് മത്സരത്തില്‍ ആര് ജയിക്കും?...,Sports Highlights and Cricket Match Updates,NaN
4981,FuruRadio #5 - Layer 2 Scaling Solutions,Blockchain and Solidity Programming,Layer 2 Scaling Solutions
16747,"JavaScript Visualized - Event Loop, Web APIs, ...",MERN Stack Web Development Tutorial,Node.js Event Loop
4752,Achilles Tendon Repair,Medical,Surgical Procedures and Techniques
1636,Distributed 2018: Consensus Algorithms,Blockchain and Solidity Programming,Consensus Algorithms Proof of Stake
12566,Day-28: What is Auditing? #audit #finance #bus...,Commerce,Financial Auditing Standards
6214,"Jaishankar Meets Jamaican PM, India Gifts BHIS...","Global Politics, News, and Current Affairs",NaN

In [37]:
df['title'] = df['title'].astype(str) + " " + df['SubTopic'].fillna('').astype(str)
df = df.drop(['SubTopic'], axis=1)

In [39]:
df.sample(20)

,title,Category
18223,Body Mind Relationship | Psychology Nursing Un...,Psychology: Behavioral Science and Mental Heal...
10553,Deep Learning(CS7015): Lec 15.3 Attention Mech...,Machine Learning and Deep Learning Course
7370,"Nclt,National Company Law Tribunal,Company के ...",Business Law and Corporate Governance
4812,USനെ വിറപ്പിച്ച് സ്പെയിനിൻ്റെ &#39;ആകാശപ്പൂട്ട...,"Global Politics, News, and Current Affairs"
3552,Zustand + React JS ❤️ #reactjs #javascript #re...,MERN Stack Web Development Tutorial
11588,Number System Tricks for UPSC PRELIMS | Prime ...,UPSC Civil Services Full Lectures and Preparation
13903,Unlock the Power of MongoDB Aggregation Framew...,MERN Stack Web Development Tutorial
19288,Study Guyton With Me | Human Physiology | MBBS...,Human Anatomy and Physiology Lectures
15011,Cloud Security Best Practices: Assessing Risks...,Cloud Computing AWS Azure
19013,CA vs CMA || Chartered Accountant vs Cost &amp...,Commerce
7841,Riverpod 2.x Course for Flutter Developers - G...,Flutter and Firebase App Development
12045,বিজেপির নতুন চিপ মিনিস্টার #trending #comedy #...,Machine Learning and Deep Learning Course
15562,GitHub Actions Tutorial - Basic Concepts and C...,Cloud Computing AWS Azure
5222,Mernstack vs Python Full Stack: Which is Better?,MERN Stack Web Development Tutorial
14454,AGRIVOLTAIC FARMING #GS3 #agrivoltaicfarming #...,Renewable Energy and Climate Science Lectures
5320,M.com 3rd sem|Investment management|Portfolio ...,Commerce
14822,Connect Firebase with Flutter Web!,Flutter and Firebase App Development
15620,"Top 3 Skill, Steps Required for Finance and Ac...",Chartered Accountancy and Financial Auditing
3436,AI শিখুন বাংলায় | Free Artificial Intelligenc...,Machine Learning and Deep Learning Course
18106,Macro 3.2- Inflationary and Recessionary Gaps ...,Commerce

In [40]:
df.to_csv('UrWay Final Dataset.csv', index=False)
print("Final dataset saved as 'UrWay Final Dataset.csv'.")

Final dataset saved as 'UrWay Final Dataset.csv'.